name: Publish page via GitHub Pages
on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: |
          wget -O - -o /dev/null "https://docs.google.com/spreadsheets/d/1w5Q2N01Szz0vNKXoG2V4ORiXfsAvre6Vk_pckevYZLk/export?format=tsv" > public/crono.tsv
          npm ci --include=dev
          npm run build
          npx gh-pages -d build
